/*
  This file is automatically generated. Any changes will be overwritten.
  Modify app.module.ts instead.
*/
import { APP_INITIALIZER } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { FormsModule } from '@angular/forms';
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { BodyModule } from '@radzen/angular/dist/body';
import { CardModule } from '@radzen/angular/dist/card';
import { ContentContainerModule } from '@radzen/angular/dist/content-container';
import { HeaderModule } from '@radzen/angular/dist/header';
import { SidebarToggleModule } from '@radzen/angular/dist/sidebar-toggle';
import { ImageModule } from '@radzen/angular/dist/image';
import { ButtonModule } from '@radzen/angular/dist/button';
import { SidebarModule } from '@radzen/angular/dist/sidebar';
import { PanelMenuModule } from '@radzen/angular/dist/panelmenu';
import { FooterModule } from '@radzen/angular/dist/footer';
import { LabelModule } from '@radzen/angular/dist/label';
import { ContentModule } from '@radzen/angular/dist/content';
import { HeadingModule } from '@radzen/angular/dist/heading';
import { DropDownDataGridModule } from '@radzen/angular/dist/dropdown-datagrid';
import { AccordionModule } from '@radzen/angular/dist/accordion';
import { TextBoxModule } from '@radzen/angular/dist/textbox';
import { TextAreaModule } from '@radzen/angular/dist/textarea';
import { GridModule } from '@radzen/angular/dist/grid';
import { FormModule } from '@radzen/angular/dist/form';
import { DropDownModule } from '@radzen/angular/dist/dropdown';
import { NumericModule } from '@radzen/angular/dist/numeric';
import { SharedModule } from '@radzen/angular/dist/shared';
import { NotificationModule } from '@radzen/angular/dist/notification';
import { DialogModule } from '@radzen/angular/dist/dialog';

import { ConfigService, configServiceFactory } from './config.service';
import { AppRoutes } from './app.routes';
import { AppComponent } from './app.component';
import { CacheInterceptor } from './cache.interceptor';
export { AppComponent } from './app.component';
import { CharactersComponent } from './characters/characters.component';
import { StatDescriptionsComponent } from './stat-descriptions/stat-descriptions.component';
import { AddStatLevelComponent } from './add-stat-level/add-stat-level.component';
import { EditStatLevelComponent } from './edit-stat-level/edit-stat-level.component';
import { NewCharacterComponent } from './new-character/new-character.component';
import { HomeComponent } from './home/home.component';
import { CharacterCompletionWarningComponent } from './character-completion-warning/character-completion-warning.component';
import { FeatLineComponent } from './feat-line/feat-line.component';
import { AddFeatLineComponent } from './add-feat-line/add-feat-line.component';
import { ShowFeatLineComponent } from './show-feat-line/show-feat-line.component';
import { AddFeatLineDescriptionComponent } from './add-feat-line-description/add-feat-line-description.component';
import { AddFeatLineStatRequirementComponent } from './add-feat-line-stat-requirement/add-feat-line-stat-requirement.component';
import { AddFeatLineFeatRequirementComponent } from './add-feat-line-feat-requirement/add-feat-line-feat-requirement.component';
import { AddFeatLineFreeFeatComponent } from './add-feat-line-free-feat/add-feat-line-free-feat.component';
import { AddFeatLineUnlockFeatComponent } from './add-feat-line-unlock-feat/add-feat-line-unlock-feat.component';
import { AddFeatActionComponent } from './add-feat-action/add-feat-action.component';
import { LoginLayoutComponent } from './login-layout/login-layout.component';
import { MainLayoutComponent } from './main-layout/main-layout.component';


export const PageDeclarations = [
  CharactersComponent,
  StatDescriptionsComponent,
  AddStatLevelComponent,
  EditStatLevelComponent,
  NewCharacterComponent,
  HomeComponent,
  CharacterCompletionWarningComponent,
  FeatLineComponent,
  AddFeatLineComponent,
  ShowFeatLineComponent,
  AddFeatLineDescriptionComponent,
  AddFeatLineStatRequirementComponent,
  AddFeatLineFeatRequirementComponent,
  AddFeatLineFreeFeatComponent,
  AddFeatLineUnlockFeatComponent,
  AddFeatActionComponent,
];

export const LayoutDeclarations = [
  LoginLayoutComponent,
  MainLayoutComponent,
];

export const AppDeclarations = [
  ...PageDeclarations,
  ...LayoutDeclarations,
  AppComponent
];

export const AppProviders = [
  {
    provide: HTTP_INTERCEPTORS,
    useClass: CacheInterceptor,
    multi: true
  },
  ConfigService,
  {
    provide: APP_INITIALIZER,
    useFactory: configServiceFactory,
    deps: [ConfigService],
    multi: true
  }
];

export const AppImports = [
  BrowserModule,
  BrowserAnimationsModule,
  FormsModule,
  HttpClientModule,
  BodyModule,
  CardModule,
  ContentContainerModule,
  HeaderModule,
  SidebarToggleModule,
  ImageModule,
  ButtonModule,
  SidebarModule,
  PanelMenuModule,
  FooterModule,
  LabelModule,
  ContentModule,
  HeadingModule,
  DropDownDataGridModule,
  AccordionModule,
  TextBoxModule,
  TextAreaModule,
  GridModule,
  FormModule,
  DropDownModule,
  NumericModule,
  SharedModule,
  NotificationModule,
  DialogModule,
  AppRoutes
];
